In [24]:
import numpy as np

In [70]:
a = np.array(range(24))

In [71]:
a = a.reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [76]:
for i in range(3):
    print(i)
    np.random.shuffle(a[:,i])
    print(a)

0
[[[12 13 14 15]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [16 17 18 19]
  [20 21 22 23]]]
1
[[[12 13 14 15]
  [16 17 18 19]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [20 21 22 23]]]
2
[[[12 13 14 15]
  [16 17 18 19]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [20 21 22 23]]]


In [80]:
a[:,0]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [81]:
np.random.shuffle(a[:,0])

In [82]:
a

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [20, 21, 22, 23]]])

In [83]:
a[:,0]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [84]:
np.random.shuffle(a[:,0])
a

array([[[ 0,  1,  2,  3],
        [16, 17, 18, 19],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [ 4,  5,  6,  7],
        [20, 21, 22, 23]]])

In [85]:
a

array([[[ 0,  1,  2,  3],
        [16, 17, 18, 19],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [ 4,  5,  6,  7],
        [20, 21, 22, 23]]])

In [86]:
np.swapaxes(a, 0, 1)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [99]:
d = {'a':0, 'b':1, 'c':23}

In [102]:
len(d)

3

In [91]:
for k, v in d.items():
    print(v)

0
1
23


In [92]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [93]:
a = np.array(a)

In [94]:
b = np.array(b)

In [96]:
c = a + b

In [97]:
c

array([ 6,  8, 10, 12])

In [98]:
list(c)

[6, 8, 10, 12]

In [103]:
a = np.array([[0,1,0,0],[1,0,0,0],[0,0,0,1]])
[np.where(r==1)[0][0] for r in a]

[1, 0, 3]

In [105]:
a.shape

(3, 4)